### ISSUE TITLE
2018-11-21 Herausforderungen bei der Zusammenarbeit zwischen Internen und Externen

### ISSUE THREAD

**Issue by danbim** [agile-lean-hl/agile-lean-hl#2]
Wer? Caro von inoio
Was? tbd.

**Comment by slightlyopaque** [comment]
In dem Vortrag geht es um einige typische Herausforderungen in Projekten, in denen interne Mitarbeiter_innen und externe Dienstleister_innen miteinander arbeiten. Hierbei gibt es häufig eine Art Culture Clash, der vorrangig indirekt ausgetragen wird und Gefahren für beide Seiten birgt. 
Mich interessiert dabei, was wir im Blick haben sollten um solche Situationen und Projekte insgesamt besser gestalten zu können.

**Comment by danbim** [comment]
Das Meetup findet statt bei der Mach AG, Wielandstraße 14, 23558 Lübeck. Vielen Dank für's Hosten!
