### ISSUE TITLE
04/2019 AgileGames@Lübeck

### ISSUE THREAD

**Issue by hansemart** [agile-lean-hl/agile-lean-hl#3]
Hi Folks,

in Hamburg findet dieser Tage gerade ein Abend zum Agilen Spiel von Judith Andresen statt:
https://www.meetup.com/de-DE/Agile-Coaching-Das-Spiel/events/255934123/

Ich kann mir gut vorstellen, dass das hier in Lübeck auch ein paar Interessierte geben wird.
Wärt ihr dabei?

BG,
Martin

**Comment by danbim** [comment]
Moin Martin! Ich finde das klingt sehr interessant und wäre auf jeden Fall dabei. Ein paar Fragen zum Vorschlag:

1. Hast Du Erfahrung mit dem Spiel und könntest das Anleiten?
2. Hast Du schon einen Termin im Sinn?
3. Kannst Du einen Raum stellen / organisieren oder brauchst Du Hilfe?
4. Wie viele Teilnehmer schweben Dir vor / machen Sinn?

MfG,
Daniel

**Comment by hansemart** [comment]
Moin Daniel,

ich kenne das Spiel noch nicht selbst, ein Kollege aber und der könnte noch
jemanden aus dem Autorenkreis zu uns organisieren.

Raum könnte Garage werden, und Termin eher März/April

Pro Spieltisch braucht man sechs Personen, mit etwas Vorlauf und Werbung
bekommen wir bestimmt genug zusammen.

BG,
Martin

Am Mo., 4. Feb. 2019, 08:22 hat Daniel Bimschas <notifications@github.com>
geschrieben:

**Comment by SinaA87** [comment]
Hi Martin,
wär es für dich ok, einen Termin im April zu organisieren? Ich würde mich dann für Ende März vordrängeln :)

**Comment by hansemart** [comment]
Ja, April sollte klappen!

Am Mo., 18. Feb. 2019, 09:17 hat SinaA87 <notifications@github.com>
geschrieben:

**Comment by danbim** [comment]
@hansemart Sorry, ich hatte den Termin gar nicht mehr auf dem Schirm. Nach wie vor Interesse das in der Zukunft zu veranstalten?

**Comment by hansemart** [comment]
Jep, es wird allerdings eher was vor den Sommerferien.
Gruß, Martin

**Comment by danbim** [comment]
Hej @hansemart ! Sind schon ein paar Tage vergangen ;-). Wenn ich mich recht erinnere hatten wir diese Spiele letztes Jahr beim Termin bei Dräger gemacht, korrekt? Dann könnte dieses Ticket hier weg? Oder willst Du (noch mal) einen Termin veranstalten?
LG Daniel

**Comment by hansemart** [comment]
Moin Daniel,

lass uns das Mal entfernen. Gerade etwas zu bunt....

Beste Grüße!
Martin

Daniel Bimschas <notifications@github.com> schrieb am Mo., 27. Apr. 2020,
08:28:
