### ISSUE TITLE
02/2019 Mind as Code - Achtsamkeit für Entwickler und Wissensarbeiter

### ISSUE THREAD

**Issue by thilko** [agile-lean-hl/agile-lean-hl#4]
Wie kann man entspannter in der Welt leben? Wie kann man sich mehr auf das konzentrieren, was während der Arbeit und im Leben wirklich wichtig ist? Wie kann man widerstandsfähiger sein, wenn die Dinge nicht so funktionieren, wie wir es wollten? Und wie kann man auf so eine Situation intelligenter reagieren?

Achtsamkeit ist eine wissenschaftlich erforschte Praxis, um den Geist zu trainieren. Es ist wie ein Wechsel zu einem neuen, nützlicheren Betriebssystem. Alles wird ein wenig einfacher. Wenn Sie Achtsamkeit trainieren, werden Sie kompetenter im Hacken Ihres Geistes: Sie lernen langsam die Programmiersprache, auf die Ihr Geist reagiert, und pflegen so eine freundlichere und fruchtbarere Beziehung zu Ihrem Geist.

Bei der Arbeit verbessert eine regelmäßiges Achtsamkeitstraining Konzentration, Gelassenheit und Impulskontrolle; Fähigkeiten, die in komplexen agilen Umgebungen nützlich sind und dringend benötigt werden.

Und während es Achtsamkeitspraktiken schon seit hunderten von Jahren gibt, hat es in den letzten 30 Jahren viel wissenschaftliche Forschung zur Achtsamkeit gegeben, die zeigt, was funktioniert und was nicht.

In diesem interaktiven Vortrag werde ich erzählen, was mich an Achtsamkeit fasziniert, wie Achtsamkeit funktioniert und warum es sich lohnt, sie zu üben. Wir schauen uns einige der wissenschaftlichen Erkenntnisse an und machen eine kurze Übung, die Sie mit nach Hause nehmen können.

All das mit Analogien zum Coden und es wird sogar ein Katzenvideo geben.

# Vita
Markus hat Backend-Systeme für große Unternehmen entwickelt und ist heute freiberuflicher Zusammenarbeits-Coach. Seine "Werkzeuge" dafür sind die agile Denkweise, hirnfreundliche Workshops, gewaltfreie Kommunikation, Theory U und Art of Hosting.

Achtsamkeit ist sein Weg, gesund, effektiv und glücklich zu bleiben inmitten all der Verrücktheit in Organisationen und der Welt. Er ist zertifizierter Trainer von "Search Inside Yourself" - dem innerhalb von Google entwickelten Programm für Achtsamkeit und emotionale Intelligenz.

**Comment by thilko** [comment]
Termin irgendwann Mitte - Ende Februar. Könnten wir das nicht wieder im MFC machen? Fand´ das ganz gut das letzte Mal...

**Comment by LueBecko** [comment]
Find ich ein tolles Thema. Ich frag einmal an ob wir das wieder bei MACH ausrichten können.

**Comment by danbim** [comment]
@thilko Hattest Du den Konferenzraum im MFC im Sinn in dem wir auch das erste Meetup gemacht haben? Oder MACH? Falls MFC, würde ich da wieder anfragen diese Woche.

**Comment by LueBecko** [comment]
Ahh, da hab ich die Communities durcheinander gebracht. Dann will ich mich da nicht nach vorne drängen. Thema finde ich trotzdem spannend :)
