### ISSUE TITLE
03/2019 OKRs - Measure what Matters (Sina Bimschas)

### ISSUE THREAD

**Issue by danbim** [agile-lean-hl/agile-lean-hl#5]
Basierend auf dem Buch "OKR - Measure What matters" von John Doerr, möchte ich das Prinzip von OKRs im Unternehmen aufzeigen und Beispiele aus dem Produktmanagement von Element erklären. Was sind OKRs? Braucht man OKRs? Wie kann man OKRs einführen? Was sind meine Erfahrungen bisher damit? Was sind die erfahrenen Vorteile/Nachteile? 

TERMIN wäre Ende März.

**Comment by SinaA87** [comment]
won't make it
