### ISSUE TITLE
2019-03-14 Vertikalisierungsprojekte (Ole Langbehn)

### ISSUE THREAD

**Issue by danbim** [agile-lean-hl/agile-lean-hl#6]
Beschreibung folgt...

**Comment by neurolabs** [comment]
### Vertikale Organisation - da muss sich was um 90° drehen im Kopf!

In einer herkömmlichen Stab-Linien-Organisation mit ISO/OSI geschichteter IT und Produktentwicklung trifft man oft Stillstand und bis zur Unbeweglichkeit durch Abhängigkeiten verknotete Roadmaps an. Daher ist es wenig verwunderlich, dass hier alte, schwer ablösbare IT-Produkte schwerfällig im Betrieb sind. In einer vertikalen Organisation arbeiten cross-funktionale Teams an einem kompletten Produkt-Stack von der Kundenschnittstelle bis zum Betrieb. Jedes dieser Teams ist für einen fachlichen Bereich, eine sogenannte Domäne, verantwortlich. Die verschiedenen fachlichen Domänen werden dabei im Sinne einer funktionalen Modularisierung durch voneinander getrennte Systeme umgesetzt. Das share-nothing Prinzip führt zu größtmöglicher Unabhängigkeit der Systeme und Teams. Dies minimiert den Kommunikationsaufwand zwischen Teams und die Anzahl der Stakeholder pro Team. Die nötige übergreifende Kommunikation findet über horizontal angelegte Communities of Practice statt. Beispiele solcher Organisationen sind XING, Otto, Breuninger, Spotify.

## Speaker

Ole Langbehn

Als “Hacking CEO” der inoio gmbh habe ich mit unseren Teams seit 2012 Hands-On bei Otto, Galeria Kaufhof und Breuninger an Vertikalen-Projekten gearbeitet und diese mitgestaltet.

**Comment by neurolabs** [comment]
Ist vorbereitet, nehme gerne Terminvorschläge an.

**Comment by danbim** [comment]
https://www.meetup.com/agile-lean-hl/events/259293246
https://www.meetup.com/Softwerkskammer-Luebeck/events/259293284

**Comment by SinaA87** [comment]
done
